### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by ghost** [polydawn/timeless#1]
You might like what the folks at [libp2p](https://libp2p.io/) are doing: https://github.com/libp2p/specs.

E.g. [Multiformats](https://multiformats.io/), a specification for self describing values.

Parts of the [ewasm](https://github.com/ewasm) project might be of interest as well.

Webassembly is interesting because it is now widely available in browsers and other environments and is a sandboxed and (mostly) deterministic execution environment. It is a comparatively simple compiler target. Most existing source files can be transformed to make them completely deterministic.

For example, [wasm-metering](https://github.com/ewasm/wasm-metering) transforms Webassembly source code such that it can be stopped deterministically after a number of instructions have been run (which should be proportional to seconds passed).

**Comment by warpfork** [comment]
Hey there, thanks for the interest and for the pointers.

Absolutely.  Timeless is hashes all the way through, and we have all sorts of things that could integrate really productively with [IPLD](https://github.com/ipfs/go-ipld-cbor/) in particular, which is backed by the same folks who work on a lot of the libp2p stuff.  (I consider the [formula hashing in repeatr](https://github.com/polydawn/go-timeless-api/blob/d1a238534f10766e74cc88124f711872ea48dcdc/repeatrHashes.go) a placeholder that should almost certainly be replaced by IPLD and that spec for canonical hashing before v1.0, for example -- our current implementation is semantically almost identical, but then if that's the case, we might as well get on a standardization bandwagon!)

There's also a lot (... LOT ...) of things going on in [IPFS](https://github.com/ipfs/ipfs) that fits closely with our goals and needs for "who cares where it is; just get me the thing for this hash" filesystems.  (We can't currently use their filesystem implementations directly, unfortunately, for a couple of reasons: they don't have all the metadata we need in the v1/current ipfs-unixFS spec (the most obvious game-over example being simply symlinks; uid/gid, device nodes, and so on are also problematic for full container filesystems); and we also need content identification hashes which are convergent regardless of storage chunking parameters (and chunking *is* currently a parameter in the IPFS system, which makes using those hashes for content identity checks... tricky (read: impossible :( )).  However, a [unixFS-v2](https://github.com/ipfs/unixfs-v2/) spec is on the way, and should knock all these issues out of the way in the future!  And that could pave the way to a ton of really interesting integrations.)

Webassembly is interesting, but something probably largely orthagonal to the Timeless Stack: it's a bit too "in particular".  The world is full of things that don't have reasonable execution environments; Timeless is here to provide a road to handling *all* of them, and knowing really anything at all about webassembly would seem the wrong direction.  (Long term, I'm also extremely wary of any logic that seems to presume that Webassembly will be The One Bytecode Spec to rule them all, and Perfect and Unchanging forever -- it *will* evolve, and it will eventually need hash-based and full-context hermetic versioning just like everything else.  I thought the JVM bytecode in java1.5 was "done" too, and surely there was no reason to bother versioning the JVMs I was using.  Let me tell you, I get a good laugh when I reflect on that.)

[Wasm-metering](https://github.com/ewasm/wasm-metering) in particular is pretty dang cool!  Thanks for for the pointer!  Decidable haltability like that is a pretty awesome property.  I'm really excited that intentionally limited things like this are popping up :)

Comparable to wasm-metering, you might also be interesting in [Skylark](https://github.com/google/skylark) for similar reasons -- it's a seemingly "powerful" language, but explicitly non-Turing-complete, and has a standard library which is incapable of sideeffects.  It's a language meant to be user-facing as is, of course, rather than a compile target of some other tools.  (Depending on your perspective and goals, this might either be more practical and easy to apply, or, perhaps much more boring.)

I think my intention for Timeless APIs at this point is to continue being almost entirely non-computable, which limits the applicability of both wasm and skylark and other tools like it to any of our core protocol design.  (The "[heft](https://github.com/polydawn/heft/blob/6e43c6757cc374c3d2a658f1524924f3a6bcd592/test.sk#L70-L189)" experiment with Skylark to generate formulas was interesting, but even restricted as it is brought a *lot* of complexity to the table as well as versioning questions; the "stellar" tool with its [serial DAGs](https://github.com/polydawn/stellar/blob/8dc00ed104b2f60a974ba8aedfaca6cee0177594/examples/recursivemodule/.timeless/module.tl) introduced in [this last release](https://github.com/polydawn/timeless/releases/tag/release%2Fv0.201) seems to be checking off all the same boxes (except terseness), and it's a lot more explicit and manageable.)  But wasm and skylark are still really interesting for building the even-higher-layers of tooling that can in turn emit the non-computable Timeless API objects, and getting expressiveness for a human author, while still having bounded power and thus being viable for minimally trusted execution on a host.  And that's something that's going to need a lot more exploration in the near future!

(P.S. I'm giving your notes repo a skim and having a ball -- so thanks for all those pointers, as well :))

**Comment by ghost** [comment]
Yeah, there will never be one standard. I still hope that a general purpose, deterministic and widely supported Wasm-like execution engine will emerge and establish itself in the next years.

I'm currently looking into finding and building alternative virtual machines with more advanced properties (such as recursive sandboxing: https://www.youtube.com/watch?v=MBymOp6bTII). Standardization is key.

Thank you very much for your response! :)
